version: '3'
services:
  app1:
    build: ./app1
    networks:
      redpr:
        aliases:
          - app1
    ports:
      - "5001:8787"
  app2:
    build: ./app2
    networks:
      redpr:
        aliases:
          - app2
    ports:
      - "5002:8989"
  nginx:
    build: ./nginx
    networks:
      redpr:
        aliases:
          - balanceador
    ports:
      - "8585:80"
    depends_on:
      - app1
      - app2
networks:
  redpr:
